services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pruebanequi
      MYSQL_USER: usuarionequi
      MYSQL_PASSWORD: passwordnequi
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nequi_network

  prueba_nequi:
    build: .
    container_name: prueba_nequi
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://localhost:3306/pruebanequi
      SPRING_R2DBC_USERNAME: usuarionequi
      SPRING_R2DBC_PASSWORD: passwordnequi
    networks:
      - nequi_network

networks:
  nequi_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local